#!/usr/bin/env php
<?php

/*    
      see www.gioexperience.com for more details
*/

define("port",61710);
touch("/etc/serc.password");
$real_pwd=file_get_contents("/etc/serc.password");

if( $argc>1 && $argv[1]=="server" )
{
	$socket = socket_create(AF_INET, SOCK_STREAM, SOL_TCP);
	$bind=false;
	echo "try listen..";
	while(!$bind)
	{
		sleep(2);
		$bind=socket_bind($socket, "0.0.0.0", port);
		echo "..";
	}
	echo "...ok\n";
	socket_listen($socket);

	while (true)
	{
		echo "waiting connection...\n";
		$stream = socket_accept($socket);
		$cmd = socket_read($stream, 1024);
		$pwd=substr($cmd,0,32);

		if( $pwd==$real_pwd )
		{
			$cmd=substr($cmd,32);
			$ret=shell_exec($cmd);
		}
		else
		{
			$ret="Auth failed!";
		}

		echo $ret;
		socket_write($stream,$ret);
		socket_close($stream);
		
	}
	socket_close($socket);
}
elseif( $argc>1 && $argv[1]=="send" )
{
	$ip=trim($argv[2]);
	$msg=trim($argv[3]);
	$msg=$real_pwd.$msg;
	
	$ret=shell_exec("echo \"$msg\" | nc -q0 $ip ".port);
	echo $ret;
}
elseif( $argc>1 && $argv[1]=="kill" )
{
	echo "serc killing... \n\n";
	exec("pkill -f '/usr/local/bin/serc server'");
	exec("pkill -f 'netcat'");
}

elseif( $argc>1 && $argv[1]=="createauth" )
{
	$user=exec("whoami");
	if( $user!="root" ) die("\nThis tool must be launched by root!\n\n");
	
	srand(time());
	$n=rand(1,99999).time();
	$pwd=md5($n);
	
	file_put_contents("/etc/serc.password",$pwd);
	chmod("/etc/serc.password",0666);
	
	echo "Created random password in /etc/serc.password\n";
	echo "Please make sure the same file is in client and in server\n\n";
}

else
{
	echo "\n";
	echo "Usage:  serc server               # start listening\n";
	echo "        serc send [ip] [message]  # send a remote command\n";
	echo "        serc kill                 # kill all instance of serc (client, server or other)\n";
	echo "        serc createauth           # create the file /etc/serc.password. The same file must\n";
	echo "                                  # be the same in client and server\n";
	echo "\n";
	die();
}

?>
